### ISSUE TITLE
lgcstat doesn't work with latest LuaJIT

### ISSUE THREAD

**Issue by spacewander** [openresty/openresty-gdb-utils#11]
When I try to use `lgcstat`, gdb raises an exception, says '没有名为 ptr32 的成员'.

After some debug works, I find the exception is raised from this line: https://github.com/openresty/openresty-gdb-utils/blob/master/luajit21.py#L2549. Some changes of LuaJIT have broken the command.

So I dig inside the LuaJIT, and figure out several interesting things.
This commit: https://github.com/openresty/luajit2/commit/cfa188f1349ba4c843394b53f270cb64635b9805, renamed `k64` to `k64p`, which caused the break directly.
However, the another one: https://github.com/openresty/luajit2/commit/9e99ccc360bc9784ebe5ce29d5fa2c72acfc5777, removed `k64p` out of the code.

I know little about the inside of LuaJIT, so I am not sure how to adapt the change.
Could you fix the problem?

**Comment by spacewander** [comment]
And `lj-gc-objs.sxx` also suffered from the same problem:
https://github.com/openresty/stapxx/blob/a6fe7b0c86b1e3dc9db4ce11fddc84242bc5216e/tapset/luajit.sxx#L306

**Comment by agentzh** [comment]
@spacewander Seems like you can just rename `k64` to `k64p` in that Python code line. Will you try it out on your side? Thanks!

**Comment by spacewander** [comment]
@agentzh 
I am afraid it doesn't work...
The recent version of LuaJIT doesn't use K64Array any more.

These two commits indicate that LuaJIT stores 64bit constants in ir instead of K64Array:
```
commit 9e99ccc360bc9784ebe5ce29d5fa2c72acfc5777
Author: Mike Pall <mike>
Date:   2016-05-23 00:27:51 +0200

    Strip out old infrastructure for 64 bit constants.

    Contributed by Peter Cawley.

commit 7fb75ccc4cf17825c1c8fe9f44ebfb0668a1b033
Author: Mike Pall <mike>
Date:   2016-05-23 00:25:29 +0200

    Embed 64 bit constants directly in the IR, using two slots.

    Contributed by Peter Cawley.
```
It seems we don't need to count 64-bit constants for the recent version of LuaJIT.

Maybe we could just use a `try...except` to separate affected code? Just like this:
```
def get_jit_state_sz(self, J):
        sz = 0

        try:
            # list of 64-bit constants
            k = mref(J['k64'], "K64Array")
            print(k)
            len = 0;
            while k:
                len += 1
                k = mref(k['next'], "K64Array")
            sz = typ("K64Array").sizeof * len
        except gdb.error:
            pass
```

**Comment by agentzh** [comment]
@yangshuxin Will you please shed some light on this? Thanks!

**Comment by yangshuxin** [comment]
@agentzh , I will. ASAP

**Comment by agentzh** [comment]
@spacewander I think this is fixed in #12. Please confirm.

**Comment by spacewander** [comment]
@agentzh 
It works. And now it's time to update https://github.com/openresty/stapxx/issues/31 :smile:

**Comment by agentzh** [comment]
@spacewander Patches welcome!
