### ISSUE TITLE
unsure how to install

### ISSUE THREAD

**Issue by CapsAdmin** [openresty/openresty-gdb-utils#16]
I'm not sure how this is supposed to be installed. Should I cd my way into the repo and then source luajit2.1.py and then run as usual? if I do this I get
```
(gdb) cd openresty-gdb-utils/
Working directory /home/caps/goluwa/data/bin/linux_x64/openresty-gdb-utils.
(gdb) source luajit21.py
Traceback (most recent call last):
 File "luajit21.py", line 4, in <module>
   import gdbutils
ImportError: No module named 'gdbutils'
(gdb) 
```
I feel like I'm missing something obvious here as I'm not very experienced with GDB.

(initially i made this issue with nothing and a + sign by accidentally hitting enter or something)

**Comment by spacewander** [comment]
The installation is documented there: https://github.com/openresty/openresty-gdb-utils#installation

Note that you need to change python's import path for importing gdbutils. It is about these two lines in the installation:
```
py import sys
py sys.path.append("/path/to/openresty-gdb-utils")
```

**Comment by CapsAdmin** [comment]
That works, thanks!
